services:
  app:
    build: .
    image: mg-dynamic-signature:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}
    volumes:
      - ./log:/app/log
